# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the action will run.
on:
  # Triggers the workflow on push and pull request events
  push:
  pull_request:
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.66.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Enable Configuration
        run: cp config.toml.${{ steps.extract_branch.outputs.branch }} config.toml

      - name: Build Page
        run: npm run build
